name: Bug Report
description: Report errors or unexpected results.
title: "[BUG]: "
labels: ["bug"]
assignees:
  - gpauloski
body:
  - type: textarea
    id: install
    attributes:
      label: How did you install ProxyStore?
      description: >
        E.g., install via pip, install from source, etc. **Note:** this will
        be rendered as console text automatically.
      placeholder: |
        $ pip install ProxyStore
        Collecting ProxyStore
        ...
        Successfully installed ProxyStore...
      render: console
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: What version of ProxyStore are you using?
      description: >
        Package version if installed via Pip or commit ID if installed
        from source.
      placeholder: v0.3.1
    validations:
      required: true

  - type: textarea
    id: freeform
    attributes:
      label: Describe the problem.
      description: >
        Please provide sample code and directions for reproducing
        your problem and what you expected to happen.
    validations:
      required: true
